apiVersion: v1
kind: Namespace
metadata:
  name: linkerd1
---
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: k8s-linkerd1
  namespace: linkerd1
spec:
  classSelector:
    matchLabels:
      tbs: "ep13"
  writeConnectionSecretToRef:
    name: k8scluster