apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstance
metadata:
  name: big-db
spec:
  forProvider:
    databaseVersion: POSTGRES_9_6
    region: us-west2
    settings:
      tier: db-custom-1-3840
      dataDiskType: PD_SSD
      dataDiskSizeGb: 10
      ipConfiguration:
        ipv4Enabled: true
        authorizedNetworks:
          - value: "0.0.0.0/0"
  writeConnectionSecretsToRef:
    name: big-db-conn
    namespace: crossplane-system
  providerRef:
    name: gcp-provider
  reclaimPolicy: Delete