apiVersion: database.crossplane.io/v1alpha1
kind: MySQLInstance
metadata:
  name: app-mysql
  namespace: okteto
spec:
  classSelector:
    matchLabels:
      app: tbs
  writeConnectionSecretToRef:
    name: mysqlconn
  engineVersion: "5.6"