apiVersion: gcp.stacks.crossplane.io/v1alpha1
kind: GCPSample
metadata:
  name: tbs-infra
spec:
  projectID: crossplane-playground
  region: us-west1
  credentialsSecretRef:
    namespace: crossplane-system
    name: gcp-account-creds
    key: credentials