apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: okteto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: okteto/hello-world:golang
        name: hello-world
        env:
          - name: TBS_MESSAGE
            value: "Hi all TBS viewers!"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: okteto
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "hello-world"
    port: 8080
  selector:
    app: hello-world