apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: k8scluster
spec:
  classSelector:
    matchLabels:
      tbs: "ep14"
  writeConnectionSecretToRef:
    name: k8scluster