apiVersion: storage.aws.crossplane.io/v1alpha3
kind: S3BucketClass
metadata:
  name: s3bucket-standard
  labels:
    tbs: episode14
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  versioning: false
  cannedACL: private
  region: us-west-2
  localPermission: ReadWrite
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete