apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "gatekeeper-system"
spec:
  sync:
    syncOnly:
      - group: "database.gcp.crossplane.io"
        version: "v1beta1"
        kind: "CloudSQLInstance"