apiVersion: container.gcp.crossplane.io/v1beta1
kind: GKECluster
metadata:
  name: testing
spec:
  forProvider:
    location: us-central1-a
    masterAuth:
      username: admin
  writeConnectionSecretToRef:
    name: testing
    namespace: crossplane-system
  providerRef:
    name: tbs-gcp
  reclaimPolicy: Delete